#include <stdio.h>
#include <stdlib.h>

int main()
{
    unsigned long long t=0;
    int year,mon,day,h,m,s;
    scanf("%d/%d/%d %d:%d:%d",&year,&mon,&day,&h,&m,&s);
    scanf("%llu",&t);
    while(t>0)
    {
        if(t>=86400)
        {
            t-=86400;
            day++;
        }
        else
        {
            if(t>=3600)
            {
                t-=3600;
                h++;
            }
            else
            {
                if(t>=60)
                {
                    t-=60;
                    m++;
                }
                else
                {
                    s+=t;
                    t=0;
                    if(s>=60)
                    {
                        s-=60;
                        m++;
                    }
                }
            }
        }
        if(m==60)
        {
            h++;
            m=0;
        }
        if(h==24)
        {
            day++;
            h=0;
        }
        if(mon==1||mon==3||mon==5||mon==7||mon==8||mon==10||mon==12)
        {
            if(day==32)
            {
                mon++;
                day=1;
            }
        }
        else
        {
            if(mon==2)
            {
                if((year%4==0&&year%100!=0)||year%400==0)
                {
                    if(day==30)
                    {
                        mon++;
                        day=1;
                    }
                }
                else
                {
                    if(day==29)
                    {
                        mon++;
                        day=1;
                    }
                }
            }
            else
            {
                if(day==31)
                {
                    mon++;
                    day=1;
                }
            }
        }
        if(mon==13)
        {
            mon=1;
            year++;
        }
    }
    printf("%d/%02d/%02d %02d:%02d:%02d",year,mon,day,h,m,s);
    return 0;
}
