#include <stdio.h>
#include <stdlib.h>

int main()
{
    int t,i;
    long long int k,j,l,m,n;
    scanf("%d",&t);
    for(i=0;i<t;i++)
    {
        scanf("%lld",&k);
        j=(k%2==0?(k/2)*(k/2):(k/2)*((k+1)/2));
        l=j%100000;
        m=j/100000%100000;
        n=j/10000000000%100000;
        if(n)
            printf("%lld",n);
        if(n>0)
        {
            if(m==0)
                printf("00000");
            else
            {
                if(m<10)
                    printf("0000%lld",m);
                else
                {
                    if(m<100)
                        printf("000%lld",m);
                    else
                    {
                        if(m<1000)
                            printf("00%lld",m);
                        else
                        {
                            if(m<10000)
                                printf("0%lld",m);
                            else
                                printf("%lld",m);
                        }
                    }
                }
            }
        }
        else
            if(m)
                printf("%lld",m);
        if(m>0||n>0)
        {
            if(l==0)
                printf("00000\n");
            else
            {
                if(l<10)
                    printf("0000%lld\n",l);
                else
                {
                    if(l<100)
                        printf("000%lld\n",l);
                    else
                    {
                        if(l<1000)
                            printf("00%lld\n",l);
                        else
                        {
                            if(l<10000)
                                printf("0%lld\n",l);
                            else
                                printf("%lld\n",l);
                        }
                    }
                }
            }
        }
        else
            printf("%lld\n",l);
    }
    return 0;
}
